name: 自动部署到宝塔服务器

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置PHP环境
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, gd, curl
        coverage: none
        
    - name: 安装Composer依赖
      run: |
        composer install --no-dev --optimize-autoloader --no-interaction
        
    - name: 运行测试
      run: |
        # 这里可以添加PHPUnit测试
        echo "运行测试..."
        
    - name: 部署到宝塔服务器
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.BAOTA_HOST }}
        username: ${{ secrets.BAOTA_USER }}
        key: ${{ secrets.BAOTA_SSH_KEY }}
        port: ${{ secrets.BAOTA_PORT }}
        script: |
          cd /www/wwwroot/webman-musk
          
          # 备份当前版本
          if [ -d "runtime" ]; then
            tar -czf /www/backup/webman-musk/backup-$(date +%Y%m%d-%H%M%S).tar.gz .
          fi
          
          # 停止服务
          if pgrep -f "webman" > /dev/null; then
            php start.php stop
          fi
          
          # 拉取最新代码
          git fetch origin
          git reset --hard origin/main
          git clean -fd
          
          # 安装依赖
          composer install --no-dev --optimize-autoloader --no-interaction
          
          # 设置权限
          chown -R www:www .
          chmod -R 755 .
          chmod -R 777 runtime/
          
          # 启动服务
          php start.php start -d
          
          # 健康检查
          sleep 5
          if curl -f -s http://127.0.0.1:8787/api-docs > /dev/null; then
            echo "部署成功！"
          else
            echo "部署失败，请检查日志"
            exit 1
          fi

  docker-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: 登录到Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: 构建并推送Docker镜像
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/webman-musk:latest
          ${{ secrets.DOCKER_USERNAME }}/webman-musk:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: 部署Docker容器到宝塔服务器
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.BAOTA_HOST }}
        username: ${{ secrets.BAOTA_USER }}
        key: ${{ secrets.BAOTA_SSH_KEY }}
        port: ${{ secrets.BAOTA_PORT }}
        script: |
          # 拉取最新镜像
          docker pull ${{ secrets.DOCKER_USERNAME }}/webman-musk:latest
          
          # 停止旧容器
          docker stop webman-musk-api || true
          docker rm webman-musk-api || true
          
          # 启动新容器
          docker run -d \
            --name webman-musk-api \
            --restart unless-stopped \
            -p 8787:8787 \
            -v /www/wwwroot/webman-musk/runtime:/app/runtime \
            -v /www/wwwroot/webman-musk/logs:/app/logs \
            ${{ secrets.DOCKER_USERNAME }}/webman-musk:latest
          
          # 健康检查
          sleep 10
          if curl -f -s http://127.0.0.1:8787/api-docs > /dev/null; then
            echo "Docker部署成功！"
          else
            echo "Docker部署失败，请检查日志"
            exit 1
          fi
