import { createApp } from 'vue';
import { createPinia } from 'pinia';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import './styles.css';
import router from './router';
import App from './App.vue';
import axios from 'axios';
const app=createApp(App);
app.use(createPinia());
app.use(ElementPlus);
app.use(router);
axios.interceptors.request.use(cfg=>{ const t=localStorage.getItem('token'); if(t){ cfg.headers={...(cfg.headers||{}), Authorization:'Bearer '+t}; } return cfg; });
app.mount('#app');